### ISSUE TITLE
Nelze zkompilovat

### ISSUE THREAD

**Issue by fan1x** [LadyMalande/SudokuTM#1]
Schazi nejake soubory (viz priloha)
![error3](https://user-images.githubusercontent.com/2750870/44752151-7f6ab880-ab1a-11e8-9ecd-ce12ed225979.png)

**Comment by fan1x** [comment]
Jak ozkouset, ze to opravdu funguje? Vyclonovat ("stahnout") si soubory z GITu do jine slozky a zkusit, jestli to pujde spustit a zkompilovat.

**Comment by LadyMalande** [comment]
Nahrála jsem chybějící soubor, přidala jsem správné umístění sudoku souborů, stáhla jsem si soubory a zkusila jsem zkompilovat program. Zkompilovat šel, nahrál hru, uložil hru a po opětovném spuštění měl i správně uložený soubor se hrou, takže už by vše mělo jít dobře zkompilovat.

**Comment by fan1x** [comment]
Když si vyclonuji vetev "master" a zkousit projekt prelozit, tak to napise (tedy stale nelze prelozit)
```
1>------ Build started: Project: sudokuTM, Configuration: Debug Any CPU ------
1>d:\Temp\SudokuTM\sudokuTM\Sudoku.cs(324,30,324,60): error CS1061: 'Sudoku' does not contain a definition for 'DoHighlightGoodNumbersCheckBox' and no extension method 'DoHighlightGoodNumbersCheckBox' accepting a first argument of type 'Sudoku' could be found (are you missing a using directive or an assembly reference?)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

**Comment by fan1x** [comment]
Druha vetev "reseni-s-dalsi-tridou-gridbutton" zkompilovat jde, ale pise nejake warnings:
```
1>------ Rebuild All started: Project: sudokuTM, Configuration: Debug Any CPU ------
1>D:\Temp\SudokuTM\sudokuTM\GridButton.cs(32,20,32,23): warning CS1591: Missing XML comment for publicly visible type or member 'GridButton.Row'
1>D:\Temp\SudokuTM\sudokuTM\GridButton.cs(32,25,32,31): warning CS1591: Missing XML comment for publicly visible type or member 'GridButton.Column'
1>D:\Temp\SudokuTM\sudokuTM\GridButton.cs(32,33,32,37): warning CS1591: Missing XML comment for publicly visible type or member 'GridButton.Cell'
1>D:\Temp\SudokuTM\sudokuTM\GridButton.cs(128,21,128,35): warning CS1591: Missing XML comment for publicly visible type or member 'GridButton.ShowNumberMenu(GridButton)'
1>D:\Temp\SudokuTM\sudokuTM\Sudoku.cs(129,9,129,10): warning CS1587: XML comment is not placed on a valid language element
1>D:\Temp\SudokuTM\sudokuTM\Sudoku.cs(305,9,305,10): warning CS1587: XML comment is not placed on a valid language element
1>  sudokuTM -> D:\Temp\SudokuTM\sudokuTM\bin\Debug\sudokuTM.exe
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

**Comment by LadyMalande** [comment]
1) Master zprovozněna, použila jsem špatný název tlačítka. Hloupá chyba.
2) Doplnila jsem XML komentáře tam, kde bylo potřeba, upravila jsem kód tak, aby nepsal další upozornění.
3) Zjednodušila jsem metodu IsInTheSameCell tak, aby využívala parametr Cell od třídy GridButton.
4) Umazala jsem nepotřebné zakomentované oblasti.
