### ISSUE TITLE
Program prestane fungovat po nenalazeni reseni

### ISSUE THREAD

**Issue by fan1x** [LadyMalande/SudokuTM#10]
Jak zopakovat:
1. Vlozit sudoku, ktere nema reseni
2. Upravit sudoku, aby slo vyresit
-> program hlasi, ze sudoku nelze vyresit.

**Comment by LadyMalande** [comment]
Doufám, že vyřešeno.
- po spuštění metody BruteForceSolving() jsem zařadila vyčištění všech textů tlačítek v seznamu ListOfNotSolvedButtons, protože jediné co dělám v metodě na nalezení řešení je, že se dívám právě na texty tlačítek
- všimla jsem si, že řešitel nefunguje ani po opětovném spuštění nového řešitele => Po spuštění řešitele spouštím Vyčištění všech tlačítek v seznamu ListOfGridButtonsSolver, protože se tam hromadila tlačítka a tím pádem program nemohl najít řešení ani po novém zadání do řešitele.
Zkoušela jsem obě možnosti - zadat neřešitelné sudoku, přepsat to konkrétní tlačítko a už mi to sudoku dořešilo. Poté jsem zkusila řešitele vypnout a z hlavního menu zase zapnout, zadat sudoku a už to taky řešilo, takže doufám, že jsem odstranila chyby, kvůli kterým to nešlo dořešit :)
