### ISSUE TITLE
Resic sudoku nefunguje, pokud je zapnute i okno pro uzivatele

### ISSUE THREAD

**Issue by fan1x** [LadyMalande/SudokuTM#12]
Jak zopakovat:
1. Otevrit nejakou (lehkou) verzi sudoku
2. Otevrit resic sudoku
3. Prepsat sudoku do resice
4. Resic hlasi, ze sudoku nelze splnit

**Comment by LadyMalande** [comment]
Vyřešeno.
- Seznamy tlačítek jsem oddělila pro Solver i pro sudoku, funkce které tyto seznamy využívají jsem upravila, aby mohly brát různé seznamy.
