### ISSUE TITLE
Sjednotit jazyk - bud vsechno anglicky nebo cesky

### ISSUE THREAD

**Issue by fan1x** [LadyMalande/SudokuTM#3]
Viz pojmenovani tlacitek: `label1`, `label2`, `Pokracovat`, `Stredni`, `Lehka`, `Konec`
- Michani ruznych jazyk
- Nedodrzovani velke/male pismena

**Comment by LadyMalande** [comment]
Nahrála jsem nové soubory, kde už by mělo být minimum vměšování malých písmen/velkých písmen, pokud jsem dobře koukala, vše jsem předělala do angličtiny.
